language: julia
os:
  - osx
  - linux
julia:
  - 1.0
notifications:
  email: false

after_success:
  - julia -e 'cd(Pkg.dir("Splittings")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())';
  - julia -e 'cd(Pkg.dir("Splittings")); Pkg.add("Documenter"); include(joinpath("docs", "make.jl"))';
