language: julia
os:
  - osx
  - linux
julia:
  - 0.7
  - nightly
notifications:
  email: false
after_success:
  - julia -e 'cd(Pkg.dir("Splittings")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())';
  - julia -e 'Pkg.add("Documenter")'
  - julia -e 'cd(Pkg.dir("Splittings")); include(joinpath("docs", "make.jl"))'
