language: julia

os:
  - osx

julia:
  - 1.0

before_install:
  - brew update
  - brew install ffmpeg
  - rm '/usr/local/include/c++' && brew install gcc@8

notifications:
  email: false

after_success:
  - julia -e 'using Pkg; cd(Pkg.dir("Splittings")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
  - julia -e 'using Pkg; cd(Pkg.dir("Splittings")); Pkg.add("Documenter"); include(joinpath("docs", "make.jl"))';
  - julia -e 'using Pkg; cd(Pkg.dir("Splittings")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder());'
