language: julia
os:
  - osx
  - linux
julia:
  - 0.7
  - 1.0
notifications:
  email: false

after_success:
  - julia -e 'using Pkg; import Splittings; joinpath(dirname(pathof(Splittings)), "..", paths...); Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder());'
  - julia -e 'using Pkg; import Splittings; joinpath(dirname(pathof(Splittings)), "..", paths...); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
  - julia -e 'using Pkg; import Splittings; joinpath(dirname(pathof(Splittings)), "..", paths...); Pkg.add("Documenter"); include(joinpath("docs", "make.jl"))';
